#!/bin/bash

python3 /usr/lib/raspiwifi/reset_device/reset.py &> reset_test.txt &

python3 /usr/lib/raspiwifi/configuration_app/app.py &> app_test.txt &

hostapd -dd /etc/hostapd/hostapd.conf &> host_test.txt &
